# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '03:00'
      timezone: 'Europe/Amsterdam'
    groups:
      all-deps:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/*'
          - 'eslint*'
          - 'biome*'
          - 'prisma*'
          - 'next-auth*'
          - 'next*'
          - '@trpc*'
          - '@prisma*'
          - '@tanstack*'
          - '@t3-oss*'
          - 'tailwind*'
          - '@discord*'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore(deps)'
    labels:
      -  'dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '03:00'
      timezone: 'Europe/Amsterdam'
    groups:
      actions:
        patterns:
          - '*'
    open-pull-requests-limit: 2
    commit-message:
      prefix: 'chore(actions)'
    labels:
      - 'dependencies'
